site_name: MkDocs Exercises Plugin
plugins:
  - exercises
  - search
repo_url: https://github.com/yves-chevallier/mkdocs-exercises
theme:
  name: material
  locale: en
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.highlight
    - search.share
    - search.suggest
    - header.autohide
  icon:
    admonition:
      exercise: octicons/mortar-board-16
      solution: octicons/trophy-16
      hint: octicons/light-bulb-16
      foobar: octicons/check-circle-16
      failure: octicons/x-circle-16
      reload: octicons/sync-16
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.html