name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
      - name: Install Python dependencies with Poetry
        run: |
          poetry install
          pip install -e .
      - name: Build Documentation with MkDocs
        run: cd docs && poetry run mkdocs gh-deploy --force